POST http://localhost:3000/api/grade
Content-Type: application/json

{
   "name": "Debutant"
}
###
GET http://localhost:3000/api/grade
Content-Type: application/json
###
PUT http://localhost:3000/api/grade
Content-Type: application/json

{
   "id": 2,
   "newData": {
      "name": "Cmille"
   }
}
###
DELETE http://localhost:3000/api/grade
Content-Type: application/json

{
   "id": 1
}