POST http://localhost:3000/api/skill
Content-Type: application/json

{
   "name": "Ruby"
}
###
GET http://localhost:3000/api/skill
Content-Type: application/json
###
PUT http://localhost:3000/api/skill
Content-Type: application/json

{
   "id": 3,
   "newData": {
      "name": "Ruby"
   }
}
###
DELETE http://localhost:3000/api/skill
Content-Type: application/json

{
   "id": 3
}