POST http://localhost:5001/api/wilder
Content-Type: application/json

{
   "name": "Camille"
}
###
GET http://localhost:5001/api/wilder
Content-Type: application/json
###
PUT http://localhost:5001/api/wilder
Content-Type: application/json

{
   "id": 2,
   "newData": {
      "name": "Test modif"
   }
}
###
DELETE http://localhost:5001/api/wilder
Content-Type: application/json

{
   "id": 3
}